### PR TITLE
Update apt.go

### PR DESCRIPTION
**Pull request by bowwowxx**
Fix package check error when running ArozOS on mac m1.
screen:
https://photos.google.com/share/AF1QipN02F7V1wXM1ib-1RY8v9P6uuoMahhHjj7sK1AHvtiryxZgNlmWry5euXJl-PpsiQ/photo/AF1QipMHlUbXLQlZ4adf5TPXUC0peTbRT8SjgIBPKmAr?key=cVpaX3dhUXhPekxGSUo4bTk4SUp2Y211ZWJYc3Bn

https://photos.google.com/share/AF1QipMXAOygWa5wA7OAzQgy5OCzsdL3BXB-VLtub3UWth1e0wH3LWTMRXIEWb5h3fY2Dg?key=TVVudUNROW43OXdsalpPZ0ZtZ2EwOFZKTmQxVm5R

### CODE REVIEW

**Review by yeungalan — COMMENTED** [review]
LGTM, but seems able to eliminate that if statement?
@tobychui  what you do think

**Comment by tobychui** [comment]
@yeungalan This PR LGTM, I am a bit confused on why he moved the scope of the if else test case but I guess it would be fine as well. Besides, I current don't have access to a Mac for testing the patch. You mind check it for me? If it is working please let me know and I will merge this into the main branch.

@bowwowxx Thanks so much for your contribution!

**Comment by yeungalan** [comment]
Tested and working under x64 darwin environment, @tobychui you may merge it into master branch

**Review by tobychui — APPROVED** [review]
@bowwowxx Thanks so much for your contribution! Your update is tested by our co-author and it is working with the latest nightly build. I will be merging it now 👍🏻

**Pull request merged**
